### ISSUE TITLE
slogan, tagline

### ISSUE THREAD

**Issue by skupi20** [Regss/metadata.filmweb.pl#10]
Reggs popraw tagline (slogan), bo filmweb znowu coś zmienił taka składnia działa poprawnie reviewBox__title[^&gt;]+&gt;([^&lt;]+) , chodzi o recenzje filmweb, recenzja użytkowników jest poprawnie.
Albo taka reviewBox__title[^&gt;]+&quot;([^&lt;]+)&quot;

**Comment by Regss** [comment]
Poprawione -> 1.4.2
