### ISSUE TITLE
Problem z importem obsady

### ISSUE THREAD

**Issue by mrpablo74** [Regss/metadata.filmweb.pl#11]
Niepoprawnie importuje obsadę filmów: nie wiem czy to niepoprawne w ogóle nazwiska czy jakieś 4-to, 5-cio planowe role ale głównej obsady nie ma (brakuje również zdjęć aktorów). Po ostatnich poprawkach jest już plakat no ale jest ten problem z obsadą. Testowane na:
- Terminator: Dark Fate (2019)
- Mr Brean's Holiday (2007)
- Contagion (2011)

Wersja pluginu Filmweb: 2.4.3
Wersja Kodi: 18.6

**Comment by Regss** [comment]
Dla podanych tytułów obsada działa poprawnie w wersji 2.4.3. Sprawdź proszę ponownie.

**Comment by mrpablo74** [comment]
Miałem wersję 2.4.3 (jak wyżej napisałem) ale idąc za Twoją sugestią ściągnąłem ZIPa teraz jeszcze raz i teraz - też niby na wersji 2.4.3 - działa :). Dziwne, bo pliki od 8 dni się nie zmieniły a jednak teraz faktycznie działa. Dzięki - issue można zatem zamknąć/odrzucic.

**Comment by mrpablo74** [comment]
MIałem wersję 2.4.3 (jak wyżej napisałem) ale idąc za Twoją sugestią ściągnąłem
