### ISSUE TITLE
Pobierana jest zła okładka

### ISSUE THREAD

**Issue by kowalsla** [Regss/metadata.filmweb.pl#3]
Nawet przy maunalnym wborze filmu pobierana jest zła okładka np. "Hercules (1997)", "Cinderellla (1950)".

**Comment by Regss** [comment]
Okładka czy fanart? W obydwu przypadkach pobiera błędnie fanart jest to spowodowane tym iż przy fanarcie scraper wspomaga się stroną www.themoviedb.org aby pobrać go w dobrej jakości ponieważ na filmwebie takowych nie ma. Na stronie tej wyszukuje po nazwie dany film i czasem błędnie go pobiera. Spróbuje przyjrzeć się temu ponownie.

**Comment by kowalsla** [comment]
Problem jest z okładką. Nie ma nawet opcji żeby wybrać inną. Wygląda na to, że problem pojawia się tylko gdy jest inny film, który ma taką samą nazwę po angielsku. 
Przykłady: 
"Cinderella (1950).mkv" pobierana jest okładka dla "Cinderella" z 2015 roku
"Madagascar (2005).mkv" pobierana jest okładka dla "Madagascar" filmu dokumentalnego z 2011

**Comment by Regss** [comment]
![screenshot000](https://cloud.githubusercontent.com/assets/1458328/21540814/61357b44-cdb2-11e6-913f-517b66b01532.png)
![screenshot001](https://cloud.githubusercontent.com/assets/1458328/21540815/6167da4e-cdb2-11e6-851d-97f2d7839fbe.png)

U mnie pobiera prawidłowo. Wersja scrapera najnowsza? 2.2.8?

**Comment by kowalsla** [comment]
Wersja scrapera 2.2.7, kodi twierdzi, że nie ma nowszej.
Zaktualizowałem ręcznie pobierając zip z githuba i rozpoznawanie działa już prawidłowo.
Dzięki za pomoc

**Comment by Regss** [comment]
Nowsza wersja 2.2.8 jest w moim repozytorium.
Zanim trafi do oficialnego musi być przetestowana

https://github.com/Regss/xbmc-regss-repository/blob/master/repo/repository.regss/repository.regss-1.2.1.zip?raw=true

**Comment by kowalsla** [comment]
Pobrałem po prostu spakowany kod z githuba i zadziałało.
Dzięki wielkie za pomoc.

**Comment by Regss** [comment]
Właśnie wrzuciłem nową wersję 2.3.0 do mojego i oficjalnego repo. Sporo poprawek.

**Comment by kowalsla** [comment]
Wielkie, dzięki jeszcze dzisiaj zaktualizuję
