### ISSUE TITLE
Nie pobiera danych wer. 2.3.6

### ISSUE THREAD

**Issue by BlackJackPL** [Regss/metadata.filmweb.pl#7]
Niestety coś siadło. Poprawnie identyfikuje tytuł filmu ale nie pobiera żadnych danych (okładki, opis, obsadę itp).

**Comment by Regss** [comment]
Zmieniony layout strony. Poprawione w 2.4.0. Sprawdźcie proszę na większych zasobach.

**Comment by BlackJackPL** [comment]
U mnie teraz działa jak powinno :) Dzięki wielkie za update Regss!
