### ISSUE TITLE
string opis filmu

### ISSUE THREAD

**Issue by skupi20** [Regss/metadata.filmweb.pl#9]
string opis filmu bazuje na filmDescriptionSection__moreText, niestety niektóre filmy mają tylko filmDescriptionSection__text, sugeruje zrobić oba, aby mieć pewność, że opis zostanie pobrany

**Comment by Regss** [comment]
Podawaj proszę przykłady (tytuły) łatwiej będzie sprawdzić mi po poprawce.

**Comment by skupi20** [comment]
Popatrz na filmy bez więcej w opisie, przykładowy film 100 KARABINÓW, tak samo używałem podobnej składni jak ty tylko, ale niestety są filmy które tego nie mają, więc dodałem drugą i fajnie się to uzupełnia.

**Comment by Regss** [comment]
Poprawione
